WIP - Debug non-determanistic error
Running `PYTEST_ARGS="-k test_drone_takeoff --pdb" make
run_tests_in_docker` yield an error in about 1/3 of the times.
The error is probably due to check before use bug.

```
        drone.mode = "GUIDED"
        while time_valid() and (drone.local_position is None):
            utils.wait(1)
        drone.arm()
        drone.takeoff(config.FLIGHT_ALTITUDE_METERS)
        # local_position.z returns negetive height (the z axis are
flipped).
        while time_valid() and (
>           -1 * drone.local_position.z < config.FLIGHT_ALTITUDE_METERS
- 2
        ):
E       AttributeError: 'NoneType' object has no attribute 'z'

system_tests/test_dr.py:227: AttributeError
```